# frozen_string_literal: true

# Gemfile
source 'https://rubygems.org'
ruby '2.5.0'

gem 'rake'

# Frameworks
gem 'sinatra'
gem 'sinatra-contrib'

group :production do
  gem 'puma'
  gem "sinatra-cross_origin"
end

group :development do
  gem 'pry-byebug'
  gem 'racksh'
  gem 'rubocop'
  gem 'shotgun'
end

group :test do
  gem 'database_cleaner-sequel'
  gem 'json_spec'
  gem 'rack-test'
  gem "factory_bot"
  gem 'rspec'
  gem 'multi_json'
  gem 'faker'
end

# Environment
gem 'dotenv'
gem'dry-system', '~> 0.19.0'

# Persistence Layer
gem 'dry-monads'
gem 'dry-validation'
gem 'pg'
gem 'sequel_pg'
gem 'rom'
gem 'rom-sql'
gem 'rom-yaml'

# Data structures
gem 'dry-schema'
gem 'json'
gem 'rubytree'